### ISSUE TITLE
Adding MFEM dev features to PyMFEM's SWIG interface: how to get started?

### ISSUE THREAD

**Issue by mdavids-cfs** [mfem/PyMFEM#256]
Hi all, and especially @sshiraiwa ,
I am considering opening a branch to include a new MFEM feature in a dev branch: 
https://github.com/mfem/mfem/tree/darcy-hdg-dev/examples

These Darcy-type operators would be helpful for some anisotropic diffusion problem's we're currently trying to run.
Specifically, I would like to add the content in these four cpp files in the `examples` folder:

- [darcyform.cpp](https://github.com/mfem/mfem/blob/darcy-hdg-dev/examples/darcyform.cpp)
- [darcyop.cpp](https://github.com/mfem/mfem/blob/darcy-hdg-dev/examples/darcyop.cpp)
- [darcyhybridization.cpp](https://github.com/mfem/mfem/blob/darcy-hdg-dev/examples/darcyhybridization.cpp)
- [darcyreduction.cpp](https://github.com/mfem/mfem/blob/darcy-hdg-dev/examples/darcyreduction.cpp)

I don't think the interface to these operators/functionalities would be too difficult to add to PyMFEM's SWIG interface, but I am also very new to SWIG, so not sure about the best way to approach this.

I my question would be:
- Is there any obvious barrier you anticipate in adding these?
- Do you have a script/readme file/some guidelines on how to get started with SWIG for PyMFEM?

Thanks for any helpful comments!
Mathias

**Comment by sshiraiwa** [comment]
Hi @mdavids-cfs It is not easy to answer this question is a short form. I don't have a documentation for how to add features. It is probably good idea to put together something in doc folder. 

SWIG works on interface (not on the implementation), which is typcially defined in a  header file (.hpp). When the MFEM team adds a new .hpp file, what I do commonly is 

* create a SWIG .i file corresponds to the .hpp. (one file in mfem/_ser and one file in mfem/_par)
* change _ser/setup.py and _par/setup.py to include the newly added .i file
* modify ser/__init__.py and par/__init__.py to load newly wrapped classes in mfem.ser (or mfem.par) namespace
* test it

As for your case,  looking at .hpp files corresponding to these 4 files, I don't see an obvious issue. However, I wonder where you are going to put these .hpp files, when they are installed. When PyMFEM is build, twe build mfem from setup.py and we call  make install. Then, SWIG wrapper codes are generated using those installed .hpp files. I am not sure if these .hpp is going to be found in the installed file tree.  
(At the moment, this is not a "set in stone" rule, and we allow to point to a file, which exists only in MFEM source code usng --mfem-source option for setup.py, in order to handle some miniapp case.)

For more detail, perhaps it is better to communicate directly.

**Comment by sshiraiwa** [comment]
Closing this. Feel free to reopen if you have any further questions.
