### ISSUE TITLE
Hypre link error with parallel builds

### ISSUE THREAD

**Issue by flow-phys** [mfem/PyMFEM#45]
I'm having trouble building the code this way on LLNL's rzgenie machine:
virtualenv python3.7 myenv
source myenv/bin/activate.csh
pip3 download mfem
pip setup.py install --with-parallel

Seems to get quite far, though fails with an mpic+++ link error:
mpic++ -pthread -shared -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/sqlite-3.26.0-a7m6nmm5j2swmqfafff6ajhbilnn6vn5/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/zlib-1.2.11-3r4cfkmx3wwfqeof4bc244yduu2mz4ur/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/bzip2-1.0.6-ocokiv4gyfgsngehfu2xclts4sh3az73/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/ncurses-6.1-hqxqcpqjsvrp5zupkgw5vlleevj5yh5t/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/expat-2.2.5-osfcbgccvn6hpz7bseedtglebyfi5qc4/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/openssl-1.1.1a-onzwgt3njper5sjgn7odvpxpxsgiokga/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/xz-5.2.4-m5oetwxbcqb6ptsufia2v5lekrn5xcxi/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/libffi-3.2.1-af4a54r5gq5mbnjzazcbrcapqmrxijak/lib64 -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/readline-7.0-e5jqqjmcjknidgwvi353pd6umpixzxr2/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gdbm-1.18.1-e2zcux636yhdpibo6ufjywbq6woale4c/lib build/temp.linux-x86_64-3.7/io_stream_wrap.o -L/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/par/lib -L/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib -L/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-3.7.2-asydydmavj2puklmx5t6cu3ruzmg2b3a/lib -Wl,-R/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/par/lib -Wl,-R/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib -Wl,-R/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib -lmfem -lHYPRE -lmetis -lpython3.7m -o /usr/WS2/olson45/pyranda/HYPRE_SAND/PyMFEM/mfem/_par/_io_stream.cpython-37m-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lHYPRE
 
A colleague independently verified the error I'm seeing.

Any ideas?  Thanks

**Comment by tzanio** [comment]
@sshiraiwa and @rw-anderson, can you help Britton?

**Comment by sshiraiwa** [comment]
@flow-phys I will try the same command inputs on my local linux box. Meantime, can you please paste the entire log message. 
pip setup.py install --with-parallel
is supposed to download/build/install HYPRE itself too. I suspect something wrong occurred earlier since it can not find HYPRE.

**Comment by sshiraiwa** [comment]
I did test it in a new virtualenv. I did
$ virtualenv  myenv
$ source myenv/bin/activate
$ pip install numpy
$ pip install mpi4py
$ pip download mfem
(after expanding it and cd to the subdir)
$ python setup.py install --with-parallel

The link line corresponding to the error is 

mpic++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/io_stream_wrap.o -L/home/shiraiwa/myenv/mfem/par/lib -L/home/shiraiwa/myenv/mfem/lib -L/home/shiraiwa/myenv/mfem/lib -Wl,--enable-new-dtags,-R/home/shiraiwa/myenv/mfem/par/lib -Wl,--enable-new-dtags,-R/home/shiraiwa/myenv/mfem/lib -Wl,--enable-new-dtags,-R/home/shiraiwa/myenv/mfem/lib -lmfem -lHYPRE -lmetis -o /home/shiraiwa/mfem-4.2.0.1/mfem/_par/_io_stream.cpython-38-x86_64-linux-gnu.so

Here -L/home/shiraiwa/myenv/mfem/lib -L/home/shiraiwa/myenv/mfem/lib are generated for -lHYPRE and -lmetis

I suspect this correspoinds to your
 -L/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib -L/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib 
but I am wondering why the path is /usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7. Since you are runing virtual env, which is "myenv", I suppose your path should include this. Or are you separately giving a prefix?

Can you check where libHYPRE.so is installed? It is done earlier phase of setup.

**Comment by flow-phys** [comment]
@sshiraiwa , thanks for the reply. I actually named my virtualenv "py3.7" (not "myenv")... I should have been precise in what I actually typed.  (just replace "myenv" with "py3.7" in my first comment.)

Hypre does appear to have install correctly; the libHYPRE.so file it located at:
/usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib64

Any thoughts?

**Comment by sshiraiwa** [comment]
I see. I forgot there is a possibility that it is installed in lib64 instead of  lib.
setup.py script assumes it is in lib. Can you try to make a link, something like
ln -s /usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib64/libHYPRE.so /usr/WS2/olson45/pyranda/HYPRE_SAND/py3.7/mfem/lib/libHYPRE.so
You probably need to do the same for METIS too. Please let me know if this works.

**Comment by sshiraiwa** [comment]
I put 4.2.0.2 in PyPI. If you haven't tried adding a link to libHYPRE.so, as mentioned above,
please try this version, if it indeed solves the problem in your environment.
Please let me know. Thank you.

**Comment by flow-phys** [comment]
> I put 4.2.0.2 in PyPI. If you haven't tried adding a link to libHYPRE.so, as mentioned above,
> please try this version, if it indeed solves the problem in your environment.
> Please let me know. Thank you.

@sshiraiwa I can confirm that the updated setup.py has fixed my build.  Thanks for the help and quick fix.
Best

**Comment by sshiraiwa** [comment]
@flow-phys Thank you for the confirmation.
